# fly.toml app configuration file generated for rag-in-goa on 2026-08-19T13:21:30+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rag-in-goa'
primary_region = 'sin'

[build]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 15

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
  arch = 'arm64'
